=== DrMaboull/M2/IngeDoc/LSA/TP/TP1/TP1-1/exo1-2-1.dtd
<!ELEMENT annuaire (personne+, societe+)>
<!ELEMENT personne (nom_personne, prenom_personne, mail?, telephones_personne, secteur, poste, commentaire_personne?)>
    <!ELEMENT nom_personne (#PCDATA)>
    <!ELEMENT prenom_personne (#PCDATA)>
    <!ELEMENT mail (#PCDATA)>
    <!ELEMENT telephones_personne (telephone_personne+)>
    <!ELEMENT telephone_personne (#PCDATA)>
    <!ELEMENT secteur (#PCDATA)>
    <!ELEMENT poste (#PCDATA)>
	<!ELEMENT commentaire_personne (#PCDATA)>
    

<!ELEMENT societe (nom_societe, branches, directeur, commentaire_societe?)>
    <!ELEMENT nom_societe (#PCDATA)>
    <!ELEMENT branches (branche+)>
        <!ELEMENT branche (enregistrement, adresse_societe, telephone_societe, ouverture, ouvres)>

            <!ELEMENT enregistrement (#PCDATA)>
            <!ELEMENT adresse_societe (#PCDATA)>
            <!ELEMENT telephone_societe (#PCDATA)>
            <!ELEMENT ouverture (#PCDATA)>
            <!ELEMENT ouvres (ouvre+)>
                <!ELEMENT ouvre (#PCDATA)>
    <!ELEMENT directeur (noms, adresse)>
        <!ELEMENT noms (nom+)>
            <!ELEMENT nom (#PCDATA)>
        <!ELEMENT adresse (#PCDATA)>
    <!ELEMENT commentaire_societe (#PCDATA)>

=== DrMaboull/M2/IngeDoc/LSA/TP/TP1/TP1-1/exo1-2-1.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no" ?>

<!DOCTYPE annuaire SYSTEM "exo1-2-1.dtd">

<annuaire>
	<personne>
		<nom_personne>Debouz</nom_personne>
		<prenom_personne>Jamel</prenom_personne>
		<mail>jamel.debouz@gmail.com</mail>
		<telephones_personne>
			<telephone_personne>0102030405</telephone_personne>
			<telephone_personne>0506070809</telephone_personne>
		</telephones_personne>
		<secteur>intermitent du spectacle</secteur>
		<poste>humoriste</poste>
		<commentaire_personne>Commentaire personnel</commentaire_personne>
	</personne>
	
	<societe>
		<nom_societe>ComedyClub</nom_societe>
		<branches>
			<branche>
				<enregistrement>sdfd</enregistrement>
				<adresse_societe>svq</adresse_societe>	
				<telephone_societe>dfzef</telephone_societe>
				<ouverture>fz</ouverture>
				<ouvres>
					<ouvre>sgfz</ouvre>
				</ouvres>
			</branche>
			<branche>
				<enregistrement>azerty</enregistrement>
				<adresse_societe>1 allee du ciel</adresse_societe>	
				<telephone_societe>0102010209</telephone_societe>
				<ouverture>2013</ouverture>
				<ouvres>
					<ouvre>28</ouvre>
				</ouvres>
			</branche>
		</branches>
		<directeur>
			<noms>
				<nom>Jose</nom>
				<nom>Mike</nom>
			</noms>
			<adresse>1 de l'annee</adresse>
		</directeur>
		<commentaire_societe>Commentaire personnel</commentaire_societe>
	</societe>
</annuaire>
